services:
  - type: web
    name: info-roblox
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: API_KEY
        value: henntaiiz_super